version: '3.7'
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5433:5432
    networks:
      - notification

  db-adapter:
    build:
      context: db-adapter
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - db
      - tg-adapter
    networks:
      - notification

  db-worker:
    build:
      context: db-worker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - db
    networks:
      - notification

  tg-adapter:
    build:
      context: tg-adapter
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user-db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - db
      - db-worker
    networks:
      - notification

networks:
  notification:
    driver: bridge