version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432

  db-adapter:
    build:
      context: db-adapter
    depends_on:
      - db
    networks:
      - notification

  db-worker:
    build:
      context: db-worker
    depends_on:
      - db
    networks:
      - notification

networks:
  notification:
    driver: bridge