version: '3.7'
services:
  event-db:
      container_name: event-db
      image: postgres
      environment:
        POSTGRES_PASSWORD: mysecretpassword
      ports:
        - 5432:5432
      networks:
        - notification

  user-db:
    container_name: user-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5433:5432
    networks:
      - notification

  db-adapter:
    build:
      context: db-adapter
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://event-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - event-db
    networks:
      - notification

  db-worker:
    build:
      context: db-worker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://event-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - event-db
    networks:
      - notification

  tg-adapter:
    build:
      context: tg-adapter
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - user-db
    networks:
      - notification

networks:
  notification:
    driver: bridge