CREATE TABLE TASK
(
    ID          BIGSERIAL NOT NULL PRIMARY KEY,
    TEXT        VARCHAR(255),
    ORIGINAL_RQ VARCHAR(255)
);

CREATE TABLE SCHEDULE
(
    ID        BIGSERIAL NOT NULL PRIMARY KEY,
    TIMESTAMP TIMESTAMPTZ,
    TASK_ID   BIGSERIAL NOT NULL
);

ALTER TABLE SCHEDULE
    ADD CONSTRAINT SCHEDULE_TASK_FK
        FOREIGN KEY (TASK_ID)
            REFERENCES TASK (ID);