spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event-db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

db-adapter-rest:
  url: http://db-adapter:8080/schedule

tg-adapter-rest:
  url: http://tg-adapter:8080/notify-user

interval: 5000

server:
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true