spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event-db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

db-adapter-rest:
  url: db-adapter

tg-adapter-rest:
  url: tg-adapter

interval: PT05S
